# Added as a sanity check, DO NOT UPLOAD to github!!!
from  __future__ import annotations
from typing import Tuple, Any, Type
from multidict import MultiDict

def md_add(*args) -> None: ...
def md_clear(*args) -> None: ...
def md_contains(*args) -> bool: ...
def md_del(*args) -> None: ...
def md_equals(*args) -> bool: ...
def md_getall(*args) -> Tuple[int, list[Any]]: ...
def md_getone(*args) -> Tuple[int, Any]: ...
def md_new(*args) -> MultiDict[Any]: ...
def md_popall(*args)  -> Tuple[int, list[Any]]: ...
def md_popitem(*args)  -> Tuple[str, Any]: ...
def md_popone(*args) -> Tuple[str, Any]: ...
def md_replace(*args) -> None: ...
def md_setdefault(*args) -> Tuple[str, Any]: ...
def md_type(*args) -> Type[MultiDict[Any]]: ...
def md_update_from_dict(*args) -> None: ...
def md_update_from_md(*args) -> None: ...
def md_update_from_seq(*args) -> None: ...
def md_version(*args) -> int: ...
